# Generated by Django 4.1.7 on 2023-04-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], default='one', max_length=10),
        ),
    ]
