# Generated by Django 4.1.7 on 2023-04-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_studentextra_cl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementStudent',
        ),
    ]
